# Generated by Django 4.0.4 on 2022-05-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioUniverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostation',
            name='description',
            field=models.TextField(default='...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiostation',
            name='language',
            field=models.CharField(default='English', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiostation',
            name='town',
            field=models.CharField(default='Lusaka', max_length=100),
            preserve_default=False,
        ),
    ]
